### ISSUE TITLE
Colorize the changed value

### ISSUE THREAD

**Issue by najaarv** [bluebill1049/react-flip-numbers#15]
Hi, first of all, this package is awesome! Good job! I'd like a feature where the changed digits are highlighted based on the previous value. Say for example, if the current value is lesser than the previous one, highlight the specific/at least all the digits in red color, and similarly, if the current value is higher than the previous one, highlight the specific/at least all the digits in green color. Is it possible already? If not, can you suggest a solution to achieve that? Thanks.

**Comment by bluebill1049** [comment]
don't think we have such a feature.

**Comment by TomPlum** [comment]
@najaarv If you're still wanting to this, you can use CSS selectors to drill down and grab the right elements. 

I also had this issue and was confused as why the API doesn't expose class names but only inline styling options.

I wrapped the component in a div and gave it a class. Then targeted it in CSS.

```
<div className={styles.wrapper}>
    <FlipNumbers {...someProps} />
</div>
```

Then in the CSS:

```
.wrapper section > span {
    // Your rules...
}
```

The `>` selector ensures it only targets the `span` children that are direct children of the `section` element (I.e. the numbers).
You can the use `.wrapper section > span:first-child` etc.. to target specific children.
