### ISSUE TITLE
New style only applied to transitioned element

### ISSUE THREAD

**Issue by TheLifeIsYours** [bluebill1049/react-flip-numbers#16]
**Describe the bug**
If you apply a text color between transitions, the color only applies to the element which transitions, and not the static element.
Say you have 10 and want to increment to 11, before you increment, the text color is white.
Then when you increment to 11, and you have set the color to be green, or red, only the numer that transitioned (from 0 to 1) will have the new applied text color.

**Expected behavior**
Expected behaviour is to have all number elements be the same numberStyle

**Screenshots**
Before Transition:
![image](https://user-images.githubusercontent.com/8008492/93826732-2bcee880-fc68-11ea-829c-f1be2749fa0b.png)

After Transition:
![image](https://user-images.githubusercontent.com/8008492/93826740-2ffb0600-fc68-11ea-8e26-906d9659249e.png)

Here's my code for the example in the screenshot:
```jsx
const Points = ({id}) => {
    const card = useRecoilValue(cardItemState(id));

    const pointStyle = {
        color: ["#f10033", "#fff", "#28c120"][card.vote + 1]
    }

    return (
        <Styled.Points>
            <FlipNumbers numberStyle={pointStyle} height={28} width={14} color="" numbers={card.points.toString()} play />
        </Styled.Points>
    );
}
```

**Desktop:**
 - OS: Window
 - Browser: Chrome
 - Version: 85.0.4183.102 (Official Build) (64-bit)

**Comment by TheLifeIsYours** [comment]
I'd also like to add a note about negative number being next to impossible to see, as the minus sign is very small, and does not take in account the given numderStyle.

This is a -2
![image](https://user-images.githubusercontent.com/8008492/93832593-7c4d4280-fc76-11ea-990c-976c3dcc4336.png)

Very hard to tell on mobile as well, when using smaller device screens.

**Comment by bluebill1049** [comment]
<img width="659" alt="Screen Shot 2020-09-22 at 2 22 32 pm" src="https://user-images.githubusercontent.com/10513364/93843972-1052f480-fcdf-11ea-9da5-2f19fba3d81a.png">

looking into those props above.

**Comment by TheLifeIsYours** [comment]
> <img alt="Screen Shot 2020-09-22 at 2 22 32 pm" width="659" src="https://user-images.githubusercontent.com/10513364/93843972-1052f480-fcdf-11ea-9da5-2f19fba3d81a.png">
> 
> looking into those props above.

Thanks, was more or less looking at the required arguments 😅

An idea could be if *noneNumberStyle* hasn't been specified yet, it could default to the defined *numberStyle*

Or have a new property called *style* which would affect the whole component. 🤔

**Comment by bluebill1049** [comment]
not sure man, it's been awhile... take a look the source code 👀

**Comment by TheLifeIsYours** [comment]
I did, some pretty tight spaghett. 🍝 😄

**Comment by bluebill1049** [comment]
haha if you think it's spaghett, please go cook yourself some food. bye 😂
