### ISSUE TITLE
Avoid blurry fonts caused by translateZ()

### ISSUE THREAD

**Issue by dmstern** [bluebill1049/react-flip-numbers#18]
**Describe the bug**
Due to the zoom that is proceeded by the `transform: translateZ()` CSS property, the fonts of the numbers appear a bit blurry.

**To Reproduce**
Example Code

```
<FlipNumbers
          height={30}
          width={18}
          play
          duration={2}
          numbers={props.year}
        />
<div>This font is sharp</div>
```

**Expected behavior**
The font appearance should be as sharp as other elements that are not translated.

**Screenshots**

![image](https://user-images.githubusercontent.com/5219707/107151955-b38e6880-6965-11eb-919d-992aeaae2bae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox 85

**Possible Solution**
https://stackoverflow.com/a/37015409/1205127

**Comment by bluebill1049** [comment]
That's the limitation with `transform`.  There is not much I do can fix/improve on that.

**Comment by letsG** [comment]
i've managed to reduce this effect with `numberStyle: { zoom: 101%; }` but still appar on helper spans (i mean which are visible during animation)
