### ISSUE TITLE
Add type definitions

### ISSUE THREAD

**Issue by silvestreh** [bluebill1049/react-flip-numbers#23]
Would be sweet if you could add a typings file for those of us using TypeScript.

This would probably suffice:

```typescript
declare module 'react-flip-numbers' {
  import React from 'react';

  export interface FlipNumbersProps {
    background?: string;
    color: string;
    delay?: number;
    duration?: number;
    height: number;
    nonNumberStyles?: React.CSSProperties;
    numbers: string;
    numberStyles?: React.CSSProperties;
    perspective?: number;
    play: boolean;
    width: number;
  }

  export default class FlipNumbers extends React.Component<FlipNumbersProps> {}
}
```

You will probably also have to include `@types/react` and `@types/react-dom` as dev dependencies.

**Comment by bluebill1049** [comment]
would you like to send a PR?

**Comment by silvestreh** [comment]
> would you like to send a PR?

Sure thing. I opened #24 :)

**Comment by bluebill1049** [comment]
thanks a lot for the PR ❤️

**Comment by silvestreh** [comment]
Can confirm it works as expected 🥳:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1133339/195460657-d741403d-6bca-47d9-abe2-39bdcc4eebad.png">

**Comment by Matteobikk90** [comment]
I think there is a spelling issue in the interface, the styles are not applied.

Style instead of styles

```
  export interface FlipNumbersProps {
    ...........,
    nonNumberStyle?: React.CSSProperties;
    numberStyle?: React.CSSProperties;
  }
```

Can you fix it please ?
