### ISSUE TITLE
Interface FlipNumbersProps wrong spelling - version:^3.0.7

### ISSUE THREAD

**Issue by Matteobikk90** [bluebill1049/react-flip-numbers#26]
**Describe the bug**
numberStyles and nonNumberStyle are not applied since the types description has an incorrect spelling

**To Reproduce**
```
export interface FlipNumbersProps {
    background?: string;
    color: string;
    delay?: number;
    duration?: number;
    height: number;
    nonNumberStyles?: React.CSSProperties;
    numbers: string;
    numberStyles?: React.CSSProperties;
    perspective?: number;
    play: boolean;
    width: number;
  }
```

**Expected behavior**
nonNumberStyles should be nonNumberStyle and numberStyles should be numberStyle

```
export interface FlipNumbersProps {
    background?: string;
    color: string;
    delay?: number;
    duration?: number;
    height: number;
    nonNumberStyle?: React.CSSProperties;
    numbers: string;
    numberStyle?: React.CSSProperties;
    perspective?: number;
    play: boolean;
    width: number;
  }
```

**Desktop (please complete the following information):**
 - OS: last mac version
 - Browser chrome

**Comment by zikiro** [comment]
@Matteobikk90  This was fixed in #25 I believe @bluebill1049 just needs to release the patch.

**Comment by bluebill1049** [comment]
I will do this after work today. thanks @zikiro

**Comment by bluebill1049** [comment]
Published.
